app.config(($routeProvider,$locationProvider)=>{
	$routeProvider
	.when("/",{
		templateUrl:"pages/home.php",
		title: 'Welcome to Home Page',
		description:"this is description"
	})
	.when("/project",{
		templateUrl:"pages/project.php",
		title:'project'
	})
	.when("/full-project/:projectid/:projectname",{
		templateUrl:"pages/full-project.php"
	})
	.when("/upload",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("./login");
				}
			}
		},
		templateUrl:"pages/upload.php"
	})
	.when("/signup",{
		templateUrl:"pages/signup.php"
	})
	.when("/login",{
		templateUrl:"pages/login.php"
	})
	.when("/blog",{
		templateUrl:"pages/blog.php"
	})
	.when("/contact",{
		templateUrl:"pages/contact-us.php"
	})
	.when("/thesis",{
		templateUrl:"pages/thesis.php"
	})
	.when("/full-thesis",{
		templateUrl:"pages/full-thesis.php"
	})
	.when("/portfolio",{
		templateUrl:"pages/portfolio.php"
	})
	.when("/full-portfolio/:name",{
		templateUrl:"pages/full-portfolio.php"
	})
	.when("/dissertation",{
		templateUrl:"pages/dissertation.php"
	})
	.when("/full-dissertation/:name",{
		templateUrl:"pages/full-dissertation.php"
	})
	.when("/thesis-report",{
		templateUrl:"pages/thesis-report.php"
	})
	.when("/full-thesis-report/:name",{
		templateUrl:"pages/full-thesis-report.php"
	})
	.when("/studentwork",{
		templateUrl:"pages/studentwork.php"
	})
	.when("/logout",{
		resolve:{
			deadResolve:($location,user,$rootScope)=>{
				user.clearData();
				$rootScope.isShow = false;
				$location.path("/");
			}
		}
	})
	.when("/dashboard",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("/");
				}
			}
		},
		templateUrl:"pages/dashboard.php"
	})
	.when("/project-upload",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("/");
				}
			}
		},
		templateUrl:"pages/upload-pages/project-upload.php"
	})
	.when("/portfolio-upload",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("/");
				}
			}
		},
		templateUrl:"pages/upload-pages/portfolio-upload.php"
	})
	.when("/post-blog",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("/");
				}
			}
		},
		templateUrl:"pages/upload-pages/post-blog.php"
	})
	.when("/thesis-upload",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("/");
				}
			}
		},
		templateUrl:"pages/upload-pages/thesis-upload.php"
	})
	.when("/dissertation-upload",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("/");
				}
			}
		},
		templateUrl:"pages/upload-pages/dissertation-upload.php"
	})
	.when("/thesis-report-upload",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("/");
				}
			}
		},
		templateUrl:"pages/upload-pages/thesis-report-upload.php"
	})
	.when("/partner-with-us",{
		/*resolve:{
			check:($location,user)=>{
				if(user.isLoggedIn()){
					$location.path("/");
				}
			}
		},*/
		templateUrl:"pages/partner-with-us.php"
	})
	.when("/forgot-password",{
		templateUrl:"pages/forgot-password.php"
	})
	.when("/blogs/:id/:name",{
		templateUrl:'pages/full-blog.php'
	})
	.when("/events",{
		templateUrl:"pages/events.php"
	})
	.when("/jobs",{
		templateUrl:"pages/jobs.php"
	})
	.when("/competition",{
		templateUrl:"pages/competition.php"
	})
	.when("/add-event",{
		templateUrl:"pages/add-event.php"
	})
	.when("/add-jobs",{
		templateUrl:"pages/add-jobs.php"
	})
	.when("/add-competition",{
		templateUrl:"pages/add-competition.php"
	})
	.when("/event",{
		templateUrl:"pages/event.php/:id"
	})
	.when("/job/:id",{
		templateUrl:"pages/job.php"
	})
	.when("/competitions/:id",{
		templateUrl:"pages/competitions.php"
	})
	.when("/plan-info",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("./");
				}
			}
		},
		templateUrl:"pages/plan-info.php"
	})
	.when("/edit-profile",{
		resolve:{
			check:($location,user)=>{
				if(!user.isLoggedIn()){
					$location.path("./");
				}
			},
		},
		templateUrl:"pages/edit-profile.php"
	})
	.when("/full-thesis/:name",{
		templateUrl:"pages/full-thesis.php"
	})
	$locationProvider.html5Mode(true);
});
// app.run(['$location', '$rootScope', function($location, $rootScope) {
//     $rootScope.$on('$routeChangeSuccess', function (event, current, previous) {
//         if (current.hasOwnProperty('$$route')) {

//             $rootScope.title = current.$$route.title;
//             $rootScope.description = current.$$route.description;
//         }
//     });
// }]);