app.config(($routeProvider,$locationProvider)=>{
	var myresolve = ()=>{
		return {
			"check":($location,saveData)=>{
				if(!saveData.isLoggedIn()){
					$location.path("./");
				}
			}
		}
	}
	$routeProvider
	.when("/",{
		templateUrl:"pages/login.php"
	})
	.when("/material",{
		resolve:myresolve(),
		templateUrl:"pages/material.php"
	})
	.when("/projects",{
		resolve:myresolve(),
		templateUrl:"pages/projects.php"
	})
	.when("/project/:id/:name",{
		resolve:myresolve(),
		templateUrl:"pages/project.php"
	})
	.when("/blogs",{
		resolve:myresolve(),
		templateUrl:"pages/blogs.php"
	})
	.when("/blog/:id/:name",{
		resolve:myresolve(),
		templateUrl:"pages/blog.php"
	})
	.when("/write-blog",{
		resolve:myresolve(),
		templateUrl:"pages/write-blog.php"
	})
	.when("/portfolio",{
		resolve:myresolve(),
		templateUrl:"pages/portfolio.php"
	})
	.when("/full-portfolio/:name",{
		resolve:myresolve(),
		templateUrl:"pages/full-portfolio.php"
	})
	.when("/thesis-report",{
		resolve:myresolve(),
		templateUrl:"pages/thesis-report.php"
	})
	.when("/full-thesis-report/:name",{
		resolve:myresolve(),
		templateUrl:"pages/full-thesis-report.php"
	})
	.when("/dessertation",{
		resolve:myresolve(),
		templateUrl:"pages/dissertation.php"
	})
	.when("/full-dessertation/:name",{
		resolve:myresolve(),
		templateUrl:"pages/full-dissertation.php"
	})
	.when("/thesis",{
		resolve:myresolve(),
		templateUrl:"pages/thesis.php"
	})
	.when("/full-thesis/:name",{
		resolve:myresolve(),
		templateUrl:"pages/full-thesis.php"
	})
	.when("/architect",{
		resolve:myresolve(),
		templateUrl:"pages/architect.php"
	})
	.when("/material-request",{
		resolve:myresolve(),
		templateUrl:"pages/material-request.php"
	})
	.when("/logout",{
		resolve:{
			deadresolve:(saveData,$location)=>{
				saveData.clearData();
				$location.path("./");
			}
		}
	})
	.otherwise({
		templateUrl:"pages/login.php"
	})
	$locationProvider.html5Mode(true);
	
});